### ISSUE TITLE
does persistence run automatically

### ISSUE THREAD

**Issue by alecmoran1** [ZonkSec/persistence-aggressor-script#6]
Hey,

Thank you so much for uploading this script. I am not sure if I followed your instructions correctly or not, but is there a way to setup the script to automatically run the desired persistence method without interacting with the beacon every time. Similar to an elevated script I have seen before. 

Thank you so much again!

**Comment by andrewchiles** [comment]
This isn't built-into the script by default because there are often multiple listeners configured on a teamserver and the operator must select the desired listener they want to persist. However, you could modify the script and hardcode it to a specific listener and add a `beacon_initial()` [function](https://www.cobaltstrike.com/aggressor-script/events.html) that will call your desired persistence technique on initial Beacon check-in.

**Comment by ZonkSec** [comment]
Thanks @andrewchiles!
